//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBConnection : DbContext
    {
        public DBConnection()
            : base("name=DBConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUST_MST> CUST_MST { get; set; }
        public virtual DbSet<USER_MST> USER_MST { get; set; }
        public virtual DbSet<BILL_HDR_TBL> BILL_HDR_TBL { get; set; }
        public virtual DbSet<BILL_TBL> BILL_TBL { get; set; }
        public virtual DbSet<PRODUCT_MST> PRODUCT_MST { get; set; }
        public virtual DbSet<SHIPPING_TBL> SHIPPING_TBL { get; set; }
    }
}
