//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_LOG_TBL
    {
        public Nullable<bool> DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string REG_USER_NAME { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string MOD_USER_NAME { get; set; }
        public string BILL_LOG_ID { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string TRANSACTION_ID { get; set; }
        public string CUST_FROM_ID { get; set; }
        public string CUST_TO_ID { get; set; }
        public string STATUS { get; set; }
        public string DISTRICT_ID_FROM { get; set; }
        public string WARD_ID_FROM { get; set; }
        public string ADDRESS_FROM { get; set; }
        public string DISTRICT_ID_TO { get; set; }
        public string WARD_ID_TO { get; set; }
        public string ADDRESS_TO { get; set; }
        public string DISTRICT_ID_CURRENT { get; set; }
        public string WARD_ID_CURRENT { get; set; }
        public string ADDRESS_CURRENT { get; set; }
        public string BRANCH_ID_CURRENT { get; set; }
        public string BRANCH_ID_TEMP { get; set; }
        public string TRANSACTION_UID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
    }
}
