//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_TBL
    {
        public string BILL_ID { get; set; }
        public Nullable<decimal> WEIGHT { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> SEND_DATE { get; set; }
        public string BILL_STATUS { get; set; }
        public Nullable<bool> DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string REG_UID { get; set; }
        public string MOD_UID { get; set; }
        public string BILL_HDR_ID { get; set; }
    
        public virtual BILL_HDR_TBL BILL_HDR_TBL { get; set; }
        public virtual USER_MST USER_MST { get; set; }
        public virtual USER_MST USER_MST1 { get; set; }
    }
}
