//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL_HDR_TBL
    {
        public int BILL_HDR_ID { get; set; }
        public Nullable<bool> DELETE_FLAG { get; set; }
        public Nullable<int> REG_ID { get; set; }
        public Nullable<int> MOD_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public Nullable<int> CUST_FROM_ID { get; set; }
        public Nullable<int> CUST_TO_ID { get; set; }
    }
}
