//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMON_ERROR
    {
        public Nullable<bool> DELETE_FLAG { get; set; }
        public string REG_USER_NAME { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string MOD_USER_NAME { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string COMMON_ERROR_ID { get; set; }
        public string COMMON_ERROR_CODE { get; set; }
        public string MESSAGE { get; set; }
    }
}
