//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUST_MST : Operator
    {
        public int CUST_ID { get; set; }
        public string CUST_NAME { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<bool> DELETE_FLAG { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public System.DateTime MOD_DATE { get; set; }
        public Nullable<int> REG_UID { get; set; }
        public Nullable<int> MOD_UID { get; set; }
    }
}

