//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_MST
    {
        public string PROD_ID { get; set; }
        public string PROD_NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<bool> DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string REG_UID { get; set; }
        public string MOD_UID { get; set; }
    
        public virtual USER_MST USER_MST { get; set; }
        public virtual USER_MST USER_MST1 { get; set; }
    }
}
