//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_MST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_MST()
        {
            this.BILL_HDR_TBL = new HashSet<BILL_HDR_TBL>();
        }
    
        public Nullable<bool> DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<System.DateTime> MOD_DATE { get; set; }
        public string REG_USER_NAME { get; set; }
        public string MOD_USER_NAME { get; set; }
        public string USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> NUMBER_LOGIN_FAIL { get; set; }
        public Nullable<System.DateTime> LAST_CHANGE_PASS { get; set; }
        public string OLD_PASSWORD { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string WARD_ID { get; set; }
        public string DISTRICT_ID { get; set; }
        public string NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL_HDR_TBL> BILL_HDR_TBL { get; set; }
        public virtual DISTRICT_MST DISTRICT_MST { get; set; }
        public virtual USER_CONFIG_MST USER_CONFIG_MST { get; set; }
        public virtual WARD_MST WARD_MST { get; set; }
    }
}
