//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuyenphatnhanh.Content.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RGlobal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RGlobal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chuyenphatnhanh.Content.Texts.RGlobal", typeof(RGlobal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không đủ quyền để thực hiện chức năng. Liên hệ quản trị viên để được giải đáp..
        /// </summary>
        public static string accessdenis {
            get {
                return ResourceManager.GetString("accessdenis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã bị khóa. Vui lòng liên hệ người quản trị để được giải quyết..
        /// </summary>
        public static string AccountLoged {
            get {
                return ResourceManager.GetString("AccountLoged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ hiện tại .
        /// </summary>
        public static string AddressCurrent {
            get {
                return ResourceManager.GetString("AddressCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi từ.
        /// </summary>
        public static string AddressFrom {
            get {
                return ResourceManager.GetString("AddressFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đến.
        /// </summary>
        public static string AddressTo {
            get {
                return ResourceManager.GetString("AddressTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống chuyển phát nhanh.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chi nhánh.
        /// </summary>
        public static string Branch_name {
            get {
                return ResourceManager.GetString("Branch_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển tới cửa hàng.
        /// </summary>
        public static string branch_temp {
            get {
                return ResourceManager.GetString("branch_temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string ChangeSuccess {
            get {
                return ResourceManager.GetString("ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET Application.
        /// </summary>
        public static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin khách hàng thành công.
        /// </summary>
        public static string CreateCustMstSuccess {
            get {
                return ResourceManager.GetString("CreateCustMstSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới thành công.
        /// </summary>
        public static string CreateSuccess {
            get {
                return ResourceManager.GetString("CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Cust_Address {
            get {
                return ResourceManager.GetString("Cust_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string Cust_District {
            get {
                return ResourceManager.GetString("Cust_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người gửi.
        /// </summary>
        public static string Cust_Name_from {
            get {
                return ResourceManager.GetString("Cust_Name_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận.
        /// </summary>
        public static string Cust_Name_To {
            get {
                return ResourceManager.GetString("Cust_Name_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Cust_Phone {
            get {
                return ResourceManager.GetString("Cust_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/Xã.
        /// </summary>
        public static string Cust_ward {
            get {
                return ResourceManager.GetString("Cust_ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng {0} đã được sửa bởi {1}.
        /// </summary>
        public static string CustMstModified {
            get {
                return ResourceManager.GetString("CustMstModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string CustName {
            get {
                return ResourceManager.GetString("CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa.
        /// </summary>
        public static string DELETE_FLAG {
            get {
                return ResourceManager.GetString("DELETE_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin khách hàng thành công.
        /// </summary>
        public static string EditCustMstSuccess {
            get {
                return ResourceManager.GetString("EditCustMstSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tên đăng nhập hoặc mật khẩu.
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại.
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm cửa hàng.
        /// </summary>
        public static string F_Branch_add {
            get {
                return ResourceManager.GetString("F_Branch_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin cửa hàng.
        /// </summary>
        public static string F_Branch_delete {
            get {
                return ResourceManager.GetString("F_Branch_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin cửa hàng.
        /// </summary>
        public static string F_Branch_edit {
            get {
                return ResourceManager.GetString("F_Branch_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý cửa hàng.
        /// </summary>
        public static string F_Branch_manager {
            get {
                return ResourceManager.GetString("F_Branch_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển hàng.
        /// </summary>
        public static string F_ChuyenHang {
            get {
                return ResourceManager.GetString("F_ChuyenHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành chuyển hàng.
        /// </summary>
        public static string F_ChuyenHangThanhCong {
            get {
                return ResourceManager.GetString("F_ChuyenHangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển hàng trả lại.
        /// </summary>
        public static string F_ChuyenHangTraLai {
            get {
                return ResourceManager.GetString("F_ChuyenHangTraLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khách hàng.
        /// </summary>
        public static string F_CustMst_add {
            get {
                return ResourceManager.GetString("F_CustMst_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa khách hàng.
        /// </summary>
        public static string F_CustMst_delete {
            get {
                return ResourceManager.GetString("F_CustMst_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa khách hàng.
        /// </summary>
        public static string F_CustMst_edit {
            get {
                return ResourceManager.GetString("F_CustMst_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm khách hàng.
        /// </summary>
        public static string F_CustMst_search {
            get {
                return ResourceManager.GetString("F_CustMst_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý khách hàng.
        /// </summary>
        public static string F_CustMstManager {
            get {
                return ResourceManager.GetString("F_CustMstManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý quận huyện.
        /// </summary>
        public static string F_DistrictMst {
            get {
                return ResourceManager.GetString("F_DistrictMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao Hàng.
        /// </summary>
        public static string F_GiaoHang {
            get {
                return ResourceManager.GetString("F_GiaoHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Giao Hàng.
        /// </summary>
        public static string F_GiaoHangThanhCong {
            get {
                return ResourceManager.GetString("F_GiaoHangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng trả lại.
        /// </summary>
        public static string F_GiaoHangTralai {
            get {
                return ResourceManager.GetString("F_GiaoHangTralai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy đơn hàng.
        /// </summary>
        public static string F_HuyDon {
            get {
                return ResourceManager.GetString("F_HuyDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển vào kho.
        /// </summary>
        public static string F_LuuKho {
            get {
                return ResourceManager.GetString("F_LuuKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển vào kho hàng trả lại.
        /// </summary>
        public static string F_LuuKhoHangTraLai {
            get {
                return ResourceManager.GetString("F_LuuKhoHangTraLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển hàng.
        /// </summary>
        public static string F_nhanChuyenHang {
            get {
                return ResourceManager.GetString("F_nhanChuyenHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Hàng.
        /// </summary>
        public static string F_NhanShipHang {
            get {
                return ResourceManager.GetString("F_NhanShipHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Quyền truy cập.
        /// </summary>
        public static string F_RoleMst {
            get {
                return ResourceManager.GetString("F_RoleMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec Role Master.
        /// </summary>
        public static string F_SecRoleMst {
            get {
                return ResourceManager.GetString("F_SecRoleMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới đơn hàng.
        /// </summary>
        public static string F_TaomoiDonHang {
            get {
                return ResourceManager.GetString("F_TaomoiDonHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả lại hàng.
        /// </summary>
        public static string F_TraHangThanhCong {
            get {
                return ResourceManager.GetString("F_TraHangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên.
        /// </summary>
        public static string F_UserMst_add {
            get {
                return ResourceManager.GetString("F_UserMst_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa nhân viên.
        /// </summary>
        public static string F_UserMst_edit {
            get {
                return ResourceManager.GetString("F_UserMst_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhân viên.
        /// </summary>
        public static string F_UserMst_manager {
            get {
                return ResourceManager.GetString("F_UserMst_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm nhân viên.
        /// </summary>
        public static string F_UserMst_search {
            get {
                return ResourceManager.GetString("F_UserMst_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhân viên.
        /// </summary>
        public static string F_UserMst_xóa {
            get {
                return ResourceManager.GetString("F_UserMst_xóa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý xã phường.
        /// </summary>
        public static string F_WardMst {
            get {
                return ResourceManager.GetString("F_WardMst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vĩ độ.
        /// </summary>
        public static string LATITUDE {
            get {
                return ResourceManager.GetString("LATITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh độ.
        /// </summary>
        public static string LONGITUDE {
            get {
                return ResourceManager.GetString("LONGITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên gói hàng.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị gói hàng.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Phiếu.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được bỏ trống.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày gửi.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng bị hủy.
        /// </summary>
        public static string Status_Cancle {
            get {
                return ResourceManager.GetString("Status_Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng trả lại được nhập vào kho.
        /// </summary>
        public static string Status_ChuyenHangHuyThanhCong {
            get {
                return ResourceManager.GetString("Status_ChuyenHangHuyThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng được nhập vào kho.
        /// </summary>
        public static string Status_ChuyenHangThanhCong {
            get {
                return ResourceManager.GetString("Status_ChuyenHangThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng đang được vận chuyển đến kho khác.
        /// </summary>
        public static string Status_dangChuyenHang {
            get {
                return ResourceManager.GetString("Status_dangChuyenHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng trả lại đang được vận chuyển đến kho khác.
        /// </summary>
        public static string Status_DangVanChuyenHangHuy {
            get {
                return ResourceManager.GetString("Status_DangVanChuyenHangHuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã giao hàng.
        /// </summary>
        public static string Status_HangShiped {
            get {
                return ResourceManager.GetString("Status_HangShiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã giao hàng trả lại.
        /// </summary>
        public static string Status_HangShipedTraLai {
            get {
                return ResourceManager.GetString("Status_HangShipedTraLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng ở kho.
        /// </summary>
        public static string Status_nhanHang {
            get {
                return ResourceManager.GetString("Status_nhanHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang giao hàng.
        /// </summary>
        public static string Status_ShipHang {
            get {
                return ResourceManager.GetString("Status_ShipHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang giao hàng trả lại.
        /// </summary>
        public static string Status_ShipHangTraLai {
            get {
                return ResourceManager.GetString("Status_ShipHangTraLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào buổi chiều.
        /// </summary>
        public static string titleloginafternoon {
            get {
                return ResourceManager.GetString("titleloginafternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúc bạn một ngày làm việc hiệu quả!.
        /// </summary>
        public static string titlelogindri {
            get {
                return ResourceManager.GetString("titlelogindri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào buổi sáng.
        /// </summary>
        public static string titleloginmoning {
            get {
                return ResourceManager.GetString("titleloginmoning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào buổi tối.
        /// </summary>
        public static string titleloginnight {
            get {
                return ResourceManager.GetString("titleloginnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string user_name {
            get {
                return ResourceManager.GetString("user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cân nặng.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
